### ISSUE TITLE
Ably::Exceptions::UnauthorizedRequest: Nonce value replayed

### ISSUE THREAD

**Issue by madzhuga** [ably/ably-ruby#202]
Hi! 

We're sending notifications using following code: 
```
ably_client = Ably::Rest.new(key: env_variable, client_id: client_id)
ably_client.post(endpoint, payload)
```

And we're getting following error from time to time: 

```
Ably::Exceptions::UnauthorizedRequest: Nonce value replayed. (See https://help.ably.io/error/40105 for help.) (status: 401, code: 40105) (code: 40105, http status: 401) -> see https://help.ably.io/error/40105 for help
```

The help.ably link explains the error but it does not help us to understand what do we do wrong? 

Thanks in advance!

**Comment by Srushtika** [comment]
Hi @madzhuga 

It's not immediately clear why this might be happening. Some explanations as to why you might be seeing this error are listed in our support article https://support.ably.com/a/solutions/articles/3000068938 but I'm that assuming you've already seen this and confirmed that there is no caching of the token in any way.

If that's the case, are you able to take some debug logs with the log level in Ably client options set to 4? Here's where you can find out more about this client option: https://www.ably.io/documentation/realtime/usage#client-options. For security reasons, please send these logs to support@ably.io instead of attaching them publicly in this GitHub issue. We can investigate the logs and get back to you with more info.

Best,
Srushtika
Dev Advocate @Ably

**Comment by madzhuga** [comment]
Hi @Srushtika ,

Thank you for your answer. I will close that ticket and follow your advice with debut logs.

Maxim
