### ISSUE TITLE
1.1.5 requires libcurl

### ISSUE THREAD

**Issue by mroach** [ably/ably-ruby#241]
During a routine dependency update I noticed that going from 1.1.4 to 1.1.5 broke in CI with the error on boot:

```
LoadError: Could not open library 'libcurl': libcurl: cannot open shared object file: No such file or directory.
Could not open library 'libcurl.so': libcurl.so: cannot open shared object file: No such file or directory.
Could not open library 'libcurl.so.4': libcurl.so.4: cannot open shared object file: No such file or directory
/usr/local/bundle/gems/ffi-1.14.2/lib/ffi/library.rb:145:in `block in ffi_lib'
```

This is caused by typhoeus depending on the external library libcurl.

A few issues here:

1. This new dependency should probably be documented. On Debian-based systems/container images, you now need to:
  `apt-get install libcurl4`
2. ~This doesn't seem like a patch-level change in accordance with Semantic Versioning since it changes dependencies not only for the gem itself, but now for the underlying operating system or container image. *Plus* it introduced new functionality: HTTP/2. I'd say that all earns at least a minor version bump.~ The library doesn't follow Semantic Version, so not a valid issue.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-721) by [Unito](https://www.unito.io/learn-more)

**Comment by owenpearson** [comment]
Hi, @mroach, thanks for reporting this to us. I'm sorry this has caused problems for you. Unfortunately our internal policy on client library versioning differs from Semantic Versioning due to `major` and `minor` being locked to our [client library feature specification](https://docs.ably.io/client-lib-development-guide/features/) version, but there are ongoing internal discussions about changing this policy so I hope we can find a solution to avoid this happening in future. You are right that we should document this new system dependency, and I apologise that we haven't done so already. I'll leave this issue open to track that addition to the documentation.

**Comment by mroach** [comment]
@owenpearson Thanks for the clarification on the version numbers. I can imagine how that's more complicated and difficult when you need to have multiple libraries out in the wild. And I can well imagine how needing libcurl slips through the cracks since it's often installed by default. A case where it's not though for example is images based on debian-slim Docker images, such as ruby-slim.

I'll strike out item 2 in the description then :)
